
server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yogi_JPA?serverTimezone=Asia/Seoul
    username: test
    password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
jwt:
  SECRET_KEY: afassakjdhajskdhlaskhdlkahlksahgkalhrskjghdlkshgjlsdahgjhsjknkfnkdsnfkjndsjkfnsjfndjsnfjkdnf
  EXP_TIME: 3600000

app:
  firebase-configuration-file: ./serviceAccountKey.json
  firebase-bucket: yogi-350dc.appspot.com

